/* Delete the existing exports_fields row. */
[SqlServer,PostgreSql,Oracle]
DELETE FROM [exports_fields] WHERE export_id = 1
[Access]
DELETE * FROM [exports_fields] WHERE export_id = 1
[All]

/* Add all the attribute fields to the new export format. */
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (1, 1, 'incid', 'incid', 1, 'incid', 1, NULL, 10, 12, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (2, 1, 'incid', 'legacy_habitat', 2, 'legacy_habitat', 2, NULL, 10, 50, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (3, 1, 'incid', 'site_ref', 3, 'site_ref', 3, NULL, 10, 16, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (4, 1, 'incid', 'site_name', 4, 'site_name', 4, NULL, 10, 100, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (5, 1, 'incid', 'boundary_base_map', 5, 'boundary_base_map', 5, NULL, 10, 20, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (6, 1, 'incid', 'digitisation_base_map', 6, 'digitisation_base_map', 6, NULL, 10, 20, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (7, 1, 'incid', 'ihs_version', 7, 'ihs_version', 7, NULL, 10, 11, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (8, 1, 'incid', 'ihs_habitat', 8, 'ihs_habitat', 8, NULL, 10, 100, 'Both')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (9, 1, 'incid_ihs_matrix', 'matrix', 3, 'ihs_matrix<no>', 9, 3, 10, 80, 'Both')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (10, 1, 'incid_ihs_formation', 'formation', 3, 'ihs_formation<no>', 10, 2, 10, 80, 'Both')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (11, 1, 'incid_ihs_management', 'management', 3, 'ihs_management<no>', 11, 2, 10, 80, 'Both')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (12, 1, 'incid_ihs_complex', 'complex', 3, 'ihs_complex<no>', 12, 2, 10, 80, 'Both')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (13, 1, 'incid_bap', 'bap_habitat', 3, 'bap_habitat', 13, 3, 10, 80, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (14, 1, 'incid_bap', 'quality_determination', 4, 'bap_quality_determination', 14, 3, 10, 80, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (15, 1, 'incid_bap', 'quality_interpretation', 5, 'bap_quality_interpretation', 15, 3, 10, 10, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (16, 1, 'incid_bap', 'interpretation_comments', 6, 'bap_interpretation_comments', 16, 3, 10, 254, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (17, 1, 'incid_sources', 'source_id', 4, 'source<no>_name', 17, 3, 10, 80, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (18, 1, 'incid_sources', 'source_date_start', 4, 'source<no>_date', 18, 3, 10, 30, 'v')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (19, 1, 'incid_sources', 'source_habitat_class', 7, 'source<no>_habitat_class', 19, 3, 10, 80, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (20, 1, 'incid_sources', 'source_habitat_type', 8, 'source<no>_habitat_type', 20, 3, 10, 100, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (21, 1, 'incid_sources', 'source_boundary_importance', 9, 'source<no>_boundary_importance', 21, 3, 10, 12, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (22, 1, 'incid_sources', 'source_habitat_importance', 10, 'source<no>_habitat_importance', 22, 3, 10, 12, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (23, 1, 'incid', 'general_comments', 9, 'general_comments', 23, NULL, 10, 254, NULL)
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (24, 1, 'incid', 'created_date', 10, 'created_date', 24, NULL, 10, 20, 'dd/MM/yyyy HH:mm:ss')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (25, 1, 'incid', 'created_user_id', 11, 'created_user', 25, NULL, 10, 100, 'Lookup')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (26, 1, 'incid', 'last_modified_date', 12, 'last_modified_date', 26, NULL, 10, 20, 'dd/MM/yyyy HH:mm:ss')
INSERT INTO [exports_fields] (export_field_id, export_id, table_name, column_name, column_ordinal, field_name, field_ordinal, fields_count, field_type, field_length, field_format) VALUES (27, 1, 'incid', 'last_modified_user_id', 13, 'last_modified_user', 27, NULL, 10, 100, 'Lookup')
